contact_links:
  - name: 📚 Read the docs
    url: https://github.com/aahnik/tgcf/wiki
    about: Make sure to go through the documentation first
  - name: 🤷 Ask a question
    url: https://github.com/aahnik/tgcf/discussions
    about: Please ask and answer questions here
